apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: influxdb-admin-credentials
data:
  admin-token: {{ .Values.adminUser.token | b64enc | quote }}
  admin-password: {{ .Values.adminUser.password | b64enc | quote }}